ExEncript/ExEncript/Models/TextoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ExEncript.Models
{
    public class TextoModel
    {
        [Key]
        [Display(Name = "ID:")]
        public int Id { get; set; }
        [Display(Name = "Texto:")]
        [Required(ErrorMessage = "Digite o Texto")]
        public string Mensagem { get; set; }
    }
}

ExEncript/ExEncript/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExEncript.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ExEncript/ExEncript/Controllers/TextoController.cs
using ExEncript.Context;
using ExEncript.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ExEncript.Controllers
{
    public class TextoController : Controller
    {
        // GET: Texto
        private Contexto db = new Contexto();
        private static string AesIV256BD = @"%j?TmFP6$BbMnY$@";
        private static string AesKey256BD = @"rxmBUJy]&,;3jKwDTzf(cui$<nc2EQr)";
        // GET: Mensagem
        public ActionResult Index()
        {
            List<TextoModel> texto = db.Textos.ToList();

            return View(texto.ToList());
        }

        #region Create - GET

        [HttpGet]
        public ActionResult Create(string? msgEncript, string? msgDecript)
        {
            if (msgEncript != null)
            {
                TempData["msgEncript"] = msgEncript;
                TempData["msgDecript"] = msgDecript;
            }

            return View();
        }
        #endregion

        #region Create - POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TextoModel textoModel)
        {
            if (ModelState.IsValid)
            {
                string msgDecript = textoModel.Mensagem;


                //AesCryptoServiceProvider
                AesCryptoServiceProvider aes = new AesCryptoServiceProvider();
                aes.BlockSize = 128;
                aes.KeySize = 256;
                aes.IV = Encoding.UTF8.GetBytes(AesIV256BD);
                aes.Key = Encoding.UTF8.GetBytes(AesKey256BD);
                aes.Mode = CipherMode.CBC;
                aes.Padding = PaddingMode.PKCS7;

                // Convertendo String para byte Arrey
                byte[] src = Encoding.Unicode.GetBytes(textoModel.Mensagem);

                //Encriptação
                using (ICryptoTransform encrypt = aes.CreateEncryptor())
                {
                    byte[] dest = encrypt.TransformFinalBlock(src, 0, src.Length);

                    textoModel.Mensagem = Convert.ToBase64String(dest);

                }
                string msgEncript = textoModel.Mensagem;
                db.Textos.Add(textoModel);
                db.SaveChanges();

                return RedirectToAction(nameof(Create), new { msgEncript = msgEncript, @msgDecript = msgDecript });
            }
            return RedirectToAction(nameof(Create));
        }
        #endregion

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TextoModel textoModel = db.Textos.Find(id);
            if (textoModel == null)
            {
                return HttpNotFound();
            }
            string msgEnc = textoModel.Mensagem;
            AesCryptoServiceProvider aes = new AesCryptoServiceProvider();
            aes.BlockSize = 128;
            aes.KeySize = 256;
            aes.IV = Encoding.UTF8.GetBytes(AesIV256BD);
            aes.Key = Encoding.UTF8.GetBytes(AesKey256BD);
            aes.Mode = CipherMode.CBC;
            aes.Padding = PaddingMode.PKCS7;
            
            byte[] src = Convert.FromBase64String(textoModel.Mensagem);
            using (ICryptoTransform decrypt = aes.CreateDecryptor())
            {
                byte[] dest = decrypt.TransformFinalBlock(src, 0, src.Length);
                textoModel.Mensagem = Encoding.Unicode.GetString(dest);
            }
            string msgDec = textoModel.Mensagem;
            TempData["msgEnc"] = msgEnc;
            TempData["msgDec"] = msgDec;
          
            return View();
        }
    }
}

ExEncript/ExEncript/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ExEncript/ExEncript/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ExEncript/ExEncript/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ExEncript/ExEncript/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Encriptar", "Create", "Texto")</li>
                    <li>@Html.ActionLink("Decriptar", "Index", "Texto")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ExEncript/ExEncript/Views/Texto/Create.cshtml
@model ExEncript.Models.TextoModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TextoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">

            @Html.LabelFor(model => model.Mensagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @{
                    if (TempData["msgDecript"] != null)
                    {
                        string msgDecript = TempData["msgDecript"].ToString();
                        @Html.Label(msgDecript.ToString());

                    }
                    else
                    {
                        @Html.EditorFor(model => model.Mensagem, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Mensagem, "", new { @class = "text-danger" })
                    }
                }

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @{
                    if (TempData["msgEncript"] == null)
                    {
                        <input type="submit" value="Enviar" class="btn btn-default" />
                    }
                }

            </div>
        </div>

        <div class="form-group">
            @{
                if (TempData["msgEncript"] != null)
                {
                    var msgEncript = TempData["msgEncript"].ToString();
                    @Html.Label("Texto Encriptado: " + msgEncript);
                }


            }

        </div>
    </div>
}

ExEncript/ExEncript/Views/Texto/Details.cshtml
@model ExEncript.Models.TextoModel

@{
    ViewBag.Title = "Details";
}

<h2>Detalhes</h2>

<div>
    <h4>Detalhes do Texto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Label("Mensagem Encriptada: ")
        </dt>

        <dd>
            @{
                var msgEnc = TempData["msgEnc"].ToString();

                @Html.Label(msgEnc);
            }
        </dd>
        <dt>
            @Html.Label("Mensagem Decriptada: ")
        </dt>

        <dd>
            @{
                var msgDec = TempData["msgDec"].ToString();

                @Html.Label(msgDec);
            }
        </dd>

    </dl>
</div>

ExEncript/ExEncript/Views/Texto/Index.cshtml
@model IEnumerable<ExEncript.Models.TextoModel>
@{
    ViewBag.Title = "Index";
}

<br />
<br />
<h2>Textos</h2>
<br />
<div class="container-fluid">
    <h1 class="h3 mb-2 text-gray-800"></h1>
    <p class="mb4">Lista de Textos</p>

    <p>


        <!-- DATATABLE-->

        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Produtos</h6>
            </div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="sisDataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th scope="col">@Html.DisplayNameFor(model => model.Mensagem)</th>

                                <th scope="col">Funções</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Mensagem)
                                        </td>
                                        <td>
                                            @Html.ActionLink("Detalhes", "Details", new { id = item.Id }) |
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </p>

</div>